exclude: '^pint/_vendor'
repos:
<<<<<<< HEAD
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
    - id: black-jupyter
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.270'
    hooks:
    - id: ruff
      args: ["--fix"]
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
=======
-   repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.10.1'
    hooks:
    -   id: isort
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
>>>>>>> 940ceef2833b47a43feeeb577c2f2702ba39bc0d
    hooks:
    - id: mdformat
      additional_dependencies:
      - mdformat-gfm  # GitHub-flavored Markdown
      - mdformat-black
-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        args: [--extra-keys=metadata.kernelspec metadata.language_info.version]
