repos:
-   repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.10.1'
    hooks:
    -   id: isort
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8

