name: CI-pint-pre

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.11", "3.13"]
        numpy: ["numpy>=2.0.0"]
        pandas: ["pandas>=3.0.0"]

    runs-on: ubuntu-latest

    env:
      TEST_OPTS: "-rfsxEX -s --cov=pint_pandas --cov-config=.coveragerc"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Get tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Install dependencies
        run: uv pip install --system "${{ matrix.numpy }}" "${{ matrix.pandas }}" ".[test]"

      - name: Install pint pre-release
        run: uv pip install --system --pre pint

      - name: Run Tests
        run: pytest $TEST_OPTS

      - name: Coverage report
        run: coverage report -m

      - name: Coveralls Parallel
        env:
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_SERVICE_NAME: github
        run: coveralls

  coveralls:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.x"
    - name: Coveralls Finished
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_SERVICE_NAME: github
      run: |
        uv pip install --system coveralls
        coveralls --finish

  # Dummy task to summarize all. See https://github.com/bors-ng/bors-ng/issues/1300
  ci-success:
    name: ci
    if: ${{ success() }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
